### ISSUE TITLE
Cleanup and Refactor Scripts

### ISSUE THREAD

**Issue by mikerourke** [mikerourke/transfermyti.me#58]
## Tasks

- [x] Replace `fs-extra` with Node.js APIs
- [x] Replace `lodash-es` with JavaScript
- [x] Remove `picocolors` and use `TaskRunner`
- [x] Remove `promise-throttle` with manual delays
